name = "AdaSouls/cardano-soulbound"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'AdaSouls/cardano-soulbound'"

[repository]
user = "AdaSouls"
project = "cardano-soulbound"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
