name = "nft/soulbound"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'nft/soulbound'"

[repository]
user = "leobel"
project = "nft/soulbound"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
